version: '3'
services:

  server:
    image: "ecdh_backend"
    command: ["/bin/server"]
    depends_on:
      - db
    environment:
      ECDH_BACKEND_REDIS: "redis://db:6379/"
    volumes:
      - "./config:/config"
    ports:
      - "4000:4000"
    networks:
      - frontend
      - backend

  db:
    image: "redis:alpine"
    networks:
      - backend

networks:
  frontend:
  backend:
