version: '3'
services:

  server:
    image: "ecdh_backend"
    command: ["/bin/server"]
    depends_on:
      - db
    environment:
      ECDH_BACKEND_REDIS: "redis://redis:6379/"
    volumes:
      - "./config:/config"
    ports:
      - "4000:4000"

  db:
    image: "redis:alpine"
    ports:
      - "6379:6379"
